---
- name: Deploy Web Server
  hosts: webserver
  become: true

  tasks:
    - name: Install Apache web server
      apt:
        name: apache2
        state: present

    - name: Create HTML file
      template:
        src: index.html.j2
        dest: ~/html/index.html

